name: sip_ua
version: 0.0.1
author: cloudwebrtc <duanweiwei1982@gmail.com>
description: A dart-lang version of the SIP UA stack.
homepage: https://github.com/cloudwebrtc/dart-sip-ua
environment:
  sdk: '>2.0.0 <3.0.0'

dependencies:
  crypto: ^2.1.2
  events2: ^0.1.3
  #flutter_webrtc: ^0.1.7
  parser_error: ^0.1.1
  sdp_transform: ^0.1.0
  uuid: ^2.0.2
  random_string: ^1.1.0


dev_dependencies:
  test: ^1.6.7